export const stateDesc = {
    GREET: 'GREET',
    ASK_NAME_MESSAGE: 'ASK_NAME_MESSAGE',
    ASK_NAME: 'ASK_NAME',
    ASK_PHONE_MESSAGE: 'ASK_PHONE_MESSAGE',
    ASK_PHONE: 'ASK_PHONE',
    ASK_EMAIL_MESSAGE: 'ASK_EMAIL_MESSAGE',
    ASK_EMAIL: 'ASK_EMAIL',
    PRINT: 'PRINT',
};

export const UPDATE_CURRENT_STATE = 'UPDATE_CURRENT_STATE';

export const reservationActionKind = {
    UPDATE_HOLDER: 'UPDATE_HOLDER',
    UPDATE_NUMBER: 'UPDATE_NUMBER',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_TYPE: 'UPDATE_TYPE',
    UPDATE_ADDRESS: 'UPDATE_ADDRESS',
    UPDATE_ITEM: 'UPDATE_ITEM',
};
