export const stateDesc = {
    GREET: 'GREET',
    ASK_NAME_MESSAGE: 'ASK_NAME_MESSAGE',
    ASK_NAME: 'ASK_NAME',
    ASK_PHONE_MESSAGE: 'ASK_PHONE_MESSAGE',
    ASK_PHONE: 'ASK_PHONE',
    ASK_EMAIL_MESSAGE: 'ASK_EMAIL_MESSAGE',
    ASK_EMAIL: 'ASK_EMAIL',
    PRINT: 'PRINT',
};

export const UPDATE_CURRENT_STATE = 'UPDATE_CURRENT_STATE';
